# -*- coding: utf-8 -*-'

# list of cohesive markers by Eli Hinkel
# Matters of Cohesion in L2 Academic texts
COHESIVE_MARKERS = [
'above all',
'accordingly',
'additionally',
'after all',
'again',
'all in all',
'all the same',
'also',
'altogether',
'and so',
'and still',
'and',
'anyhow',
'anyway',
'anyways',
'as a consequence',
'as a matter of fact',
'as a result',
'as in consequence',
'as well',
'at any rate',
'at last',
'at the same time',
'because of',
'besides',
'better still',
'but also',
'but then',
'but yet',
'but',
'by the same token',
'by the way',
'consequently',
'conversely',
'despite',
'either',
'else',
'even worse',
'eventually',
'except',
'finally',
'first of all',
'first',
'firstly',
'for all that',
'for one thing',
'for that reason',
'fourth',
'fourthly',
'furthermore',
'hence',
'however',
'in addition',
'in any case',
'in any event',
'in conclusion',
'in contrast to',
'in contrast with',
'in contrast',
'in fact',
'in place of',
'in spite of',
'in sum',
'in that case',
'in that way',
'in the event of',
'in the first place',
'in the meantime',
'in the meanwhile',
'in the same way',
'in the second place',
'in the third place',
'in this way',
'incidentally',
'instead of',
'lastly',
'likewise',
'meantime',
'meanwhile',
'moreover',
'neither',
'nevertheless',
'next',
'nonetheless',
'nor',
'not only',
'now',
'on the contrary',
'on the other hand',
'once',
'one again',
'originally',
'otherwise',
'rather',
'second of all',
'second',
'secondly',
'similarly',
'somehow',
'still',
'subsequently',
'that said',
'then again',
'then',
'therefore',
'third of all',
'third',
'thirdly',
'though',
'thus',
'to begin with',
'to conclude',
'to start with',
'to sum up',
'to summarize',
'unlike',
'yet'
]